[package]
name = "a2"
version = "0.5.0-alpha.7"
authors = [
  "Julius de Bruijn <julius@nauk.io>",
  "Sergey Tkachenko <seriy.tkachenko@gmail.com>", 
]
license = "MIT"
readme  = "README.md"
description = "A native, asynchronous Apple push notification client"
keywords    = ["apns", "apple", "push", "async", "http2"]
repository  = "https://github.com/pimeys/a2.git"
homepage    = "https://github.com/pimeys/a2"
documentation = "https://docs.rs/a2"
edition = "2018"

[dependencies]
serde = "1.0"
erased-serde = "0.3"
serde_derive = "1.0"
serde_json = "1.0"
openssl = "0.10"
futures-preview = "0.3.0-alpha.19"
http = "0.1"
base64 = "0.9"
time = "0.1"
log = "0.4"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-alpn = "0.2.0-alpha.6"
async-std = "0.99"

[dev-dependencies]
argparse = "0.2"
pretty_env_logger = "0.3"
indoc = "0.2"
tokio = "0.2.0-alpha.6"
